/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.hello

import io.ktor.server.engine.*
import io.ktor.server.netty.*
import kt.hello.router.configureRouting

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(
        App().greeting
    )
    embeddedServer(
        Netty, port = 8080, host = "127.0.0.1"
    ) {
        configureRouting()
    }.start(wait = true)
}
