/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.hello

import kt.hello.service.HelloWorldServer

class App {
    val greeting: String
        get() {
            return "Hello, gRPC server!"
        }
}

fun main() {
    println(
        App().greeting
    )
    val port = System.getenv("PORT")?.toInt() ?: 50051
    val server = HelloWorldServer(port)
    server.start()
    server.blockUntilShutdown()
}
